--
-- PostgreSQL database dump
--

-- Dumped from database version 12.3
-- Dumped by pg_dump version 12.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: processed_goods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.processed_goods (
    pg_id integer NOT NULL,
    date date DEFAULT CURRENT_DATE,
    "time" time without time zone DEFAULT CURRENT_TIME,
    product_id integer NOT NULL,
    quantity_produced integer NOT NULL,
    quantity_used integer NOT NULL,
    stock_left real
);


ALTER TABLE public.processed_goods OWNER TO postgres;

--
-- Name: processed_goods_pg_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.processed_goods ALTER COLUMN pg_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.processed_goods_pg_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: raw_milk; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.raw_milk (
    id integer NOT NULL,
    date date DEFAULT CURRENT_DATE NOT NULL,
    "time" time without time zone DEFAULT CURRENT_TIME,
    raw_milk real NOT NULL,
    stock real
);


ALTER TABLE public.raw_milk OWNER TO postgres;

--
-- Name: raw_milk_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.raw_milk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.raw_milk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: processed_goods; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.processed_goods (pg_id, date, "time", product_id, quantity_produced, quantity_used, stock_left) FROM stdin;
1	2020-05-26	01:11:43.97675	1	23	46	\N
2	2020-05-26	01:25:57.119394	4	500	460	\N
3	2020-05-26	01:26:23.90199	4	500	460	\N
4	2020-05-26	01:26:54.654533	4	500	460	\N
5	2020-06-01	22:45:52.243901	10	1	40	\N
6	2020-06-02	00:17:43.040269	10	10	20	\N
7	2020-06-02	00:19:07.725523	10	10	20	\N
8	2020-06-02	00:19:43.707434	80	80	80	\N
9	2020-06-02	00:26:19.565221	90	90	90	1000
10	2020-06-07	23:15:21.351644	90	555	460	500
13	2020-06-08	19:02:46.844806	90	-250	0	1000
14	2020-06-08	19:05:30.724159	90	-100	0	900
11	2020-06-07	23:21:32.880689	9	99	999	700
15	2020-06-08	22:12:08.017918	90	-100	0	800
16	2020-06-08	22:28:19.587161	90	-100	0	700
17	2020-06-08	22:29:59.017066	90	-100	0	600
18	2020-06-08	22:36:02.873944	90	-100	0	500
19	2020-06-08	22:36:02.927602	9	-100	0	600
20	2020-06-08	22:37:14.299112	90	-100	0	400
21	2020-06-09	12:55:42.875251	90	-100	0	300
22	2020-06-11	00:52:45.737711	90	-100	0	200
23	2020-06-11	00:59:56.763208	90	-190	0	999
24	2020-06-11	01:00:57.1082	90	-190	0	809
25	2020-06-11	01:06:47.736164	90	-190	0	619
26	2020-06-11	01:18:19.665322	90	-19	0	600
27	2020-06-11	01:20:40.036604	90	-19	0	581
28	2020-06-11	13:14:54.695784	90	-99	0	482
29	2020-06-11	18:39:00.065671	90	-90	0	392
\.


--
-- Data for Name: raw_milk; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.raw_milk (id, date, "time", raw_milk, stock) FROM stdin;
4	2020-05-24	23:54:56.088648	9	\N
5	2020-05-25	16:04:29.499315	35	\N
6	2020-05-25	16:56:55.057324	33	\N
7	2020-05-25	23:26:59.039784	90	0
8	2020-06-02	00:08:42.413356	10	10
9	2020-06-02	00:17:43.035062	0	-10
10	2020-06-02	00:19:07.721394	0	-30
11	2020-06-02	00:19:43.703542	0	90
12	2020-06-02	00:26:19.555942	0	0
13	2020-06-02	00:32:51.664243	10	10
3	2020-05-22	23:32:51.065603	10	\N
14	2020-06-02	13:46:19.559663	10	5000
15	2020-06-07	23:15:21.326024	0	4540
16	2020-06-07	23:21:32.873317	0	3541
17	2020-06-11	17:58:57.873484	1000	4541
\.


--
-- Name: processed_goods_pg_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.processed_goods_pg_id_seq', 29, true);


--
-- Name: raw_milk_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.raw_milk_id_seq', 17, true);


--
-- Name: processed_goods processed_goods_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.processed_goods
    ADD CONSTRAINT processed_goods_pkey PRIMARY KEY (pg_id);


--
-- Name: raw_milk raw_milk_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raw_milk
    ADD CONSTRAINT raw_milk_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

